### ISSUE TITLE
Player FPS;Memory;Plugin;Misc not working

### ISSUE THREAD

**Issue by erwan32** [Pinkstink-Rust/Rust-Server-Metrics#6]
Hello, 
On my grafana dashboard, some graphs are not loading since a while.
I tried to drop the Oxide mesurement serie to see if it was changing this but that changed nothing.
This is actually hapenning for "Misc Time Warnings, Plugin Hook Times, Player FPS and Player memory."
All the other graphs of the dashboard are loading fine.

No other Issues opened for this so I look to be the only-one, I dont know what can be the issue from my side, if you got an idea ?
Thanks anyway
 
![image](https://user-images.githubusercontent.com/80983029/217085364-0e2dad70-882b-4e79-bf63-70e6259054fb.png)
![image](https://user-images.githubusercontent.com/80983029/217085876-c5f3b050-08b4-4d26-beff-35a083e74d9e.png)

**Comment by features-not-bugs** [comment]
Hi, this can be due to partial database writes.

Check your server console for http error responses emitted by the plugin and enable debug logging in the config to see the raw response for influx for further information. 

Also, ensure you have followed step 2 in the readme, if you do not there will be partial write errors eventually, which can result in this behavior you have described.

**Comment by features-not-bugs** [comment]
I've just released a new version which should resolve this issue, please update and let me know how it goes.

**Comment by erwan32** [comment]
Hi
Step 2 is was made following the readme.
I Updated the plugin yesterday, but the issue is still the same
Im gonna delete the DB & remake one to see if it works. Thanks anyway !

**Comment by erwan32** [comment]
Deleted the DB & re made a new one and all is fine now
